<?php
require_once '../config/config.php';

if (!isLoggedIn()) {
    die('Not authenticated');
}

$format = $_GET['format'] ?? 'csv';
$report_type = $_GET['type'] ?? 'daily';
$date_from = $_GET['date_from'] ?? date('Y-m-d');
$date_to = $_GET['date_to'] ?? date('Y-m-d');

$database = new Database();
$db = $database->getConnection();

// Get sales data
$where_clause = "WHERE DATE(s.created_at) BETWEEN :date_from AND :date_to";
$params = [
    ':date_from' => $date_from,
    ':date_to' => $date_to
];

// Get sales with items
$query = "SELECT s.*, u.username, 
          GROUP_CONCAT(CONCAT(p.name, ' (', si.quantity, ')') SEPARATOR ', ') as items
          FROM sales s 
          LEFT JOIN users u ON s.user_id = u.id
          LEFT JOIN sales_items si ON s.id = si.sale_id
          LEFT JOIN products p ON si.product_id = p.id
          $where_clause
          GROUP BY s.id
          ORDER BY s.created_at DESC";

$stmt = $db->prepare($query);
foreach ($params as $key => $value) {
    $stmt->bindValue($key, $value);
}
$stmt->execute();
$sales = $stmt->fetchAll(PDO::FETCH_ASSOC);

if ($format === 'csv') {
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="sales_report_' . $date_from . '_to_' . $date_to . '.csv"');

    $output = fopen('php://output', 'w');

    // CSV headers
    fputcsv($output, ['Transaction ID', 'Date', 'Time', 'Cashier', 'Payment Method', 'Total Amount', 'Tax Amount', 'Items']);

    foreach ($sales as $sale) {
        fputcsv($output, [
            $sale['transaction_id'],
            date('Y-m-d', strtotime($sale['created_at'])),
            date('H:i:s', strtotime($sale['created_at'])),
            $sale['username'] ?? 'Unknown',
            strtoupper($sale['payment_method']),
            number_format($sale['total_amount'], 2),
            number_format($sale['tax_amount'], 2),
            $sale['items'] ?? ''
        ]);
    }

    fclose($output);
} elseif ($format === 'pdf') {
    // For PDF export, we'll use a simple HTML to PDF approach
    header('Content-Type: text/html');
    header('Content-Disposition: attachment; filename="sales_report_' . $date_from . '_to_' . $date_to . '.html"');

    $settings = getSettings($db);
?>
    <!DOCTYPE html>
    <html>

    <head>
        <title>Sales Report - <?php echo $date_from; ?> to <?php echo $date_to; ?></title>
        <style>
            body {
                font-family: Arial, sans-serif;
                margin: 20px;
            }

            .header {
                text-align: center;
                margin-bottom: 30px;
            }

            .report-info {
                margin-bottom: 20px;
            }

            table {
                width: 100%;
                border-collapse: collapse;
                margin-top: 20px;
            }

            th,
            td {
                border: 1px solid #ddd;
                padding: 8px;
                text-align: left;
            }

            th {
                background-color: #f2f2f2;
            }

            .total {
                font-weight: bold;
                background-color: #f9f9f9;
            }
        </style>
    </head>

    <body>
        <div class="header">
            <h1><?php echo htmlspecialchars($settings['store_name']); ?></h1>
            <h2>Sales Report</h2>
            <p>Period: <?php echo $date_from; ?> to <?php echo $date_to; ?></p>
        </div>

        <div class="report-info">
            <p><strong>Report Generated:</strong> <?php echo date('Y-m-d H:i:s'); ?></p>
            <p><strong>Generated By:</strong> <?php echo $_SESSION['username']; ?></p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>Transaction ID</th>
                    <th>Date & Time</th>
                    <th>Cashier</th>
                    <th>Payment Method</th>
                    <th>Total Amount</th>
                    <th>Tax Amount</th>
                    <th>Items</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $total_amount = 0;
                $total_tax = 0;
                foreach ($sales as $sale):
                    $total_amount += $sale['total_amount'];
                    $total_tax += $sale['tax_amount'];
                ?>
                    <tr>
                        <td><?php echo htmlspecialchars($sale['transaction_id']); ?></td>
                        <td><?php echo date('Y-m-d H:i', strtotime($sale['created_at'])); ?></td>
                        <td><?php echo htmlspecialchars($sale['username'] ?? 'Unknown'); ?></td>
                        <td><?php echo strtoupper($sale['payment_method']); ?></td>
                        <td>$<?php echo number_format($sale['total_amount'], 2); ?></td>
                        <td>$<?php echo number_format($sale['tax_amount'], 2); ?></td>
                        <td><?php echo htmlspecialchars($sale['items'] ?? ''); ?></td>
                    </tr>
                <?php endforeach; ?>
                <tr class="total">
                    <td colspan="4"><strong>TOTAL</strong></td>
                    <td><strong>$<?php echo number_format($total_amount, 2); ?></strong></td>
                    <td><strong>$<?php echo number_format($total_tax, 2); ?></strong></td>
                    <td></td>
                </tr>
            </tbody>
        </table>

        <div style="margin-top: 30px; text-align: center;">
            <p>--- End of Report ---</p>
        </div>
    </body>

    </html>
<?php
}
?>